[package]
name = "myDevice"
version = "0.1.0"
authors = ["Logan Crecraft <logandalec@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.2.0"
regex = "1.7.1"
rfd = "0.11.2"
