[package]
name = "device_manager"
version = "0.1.0"
authors = ["Logan Crecraft <logandalec@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.2.0"
trakpod = {path = "../trakpod"}
